---
- name: "Install DataBase and start it"
  hosts: localhost
  roles:
  - mysql
  tags:
  - dbinstall

- name: "Install Ghost and start it"
  hosts: localhost
  roles:
  - ghost
  tags:
  - ghostinstall